sonar.projectKey=task-buddy-backend
sonar.organization=psergio984
sonar.projectName=Task Buddy Backend
sonar.python.version=3.11
sonar.sources=app
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
