"""add priority to tasks

Revision ID: 2935b98be508
Revises: 38d622ba3db7
Create Date: 2026-05-09 02:57:39.001218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2935b98be508'
down_revision: Union[str, Sequence[str], None] = '38d622ba3db7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the taskpriority type
    taskpriority = sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority')
    taskpriority.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('tbl_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority'), nullable=False, server_default='MEDIUM'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_tasks', schema=None) as batch_op:
        batch_op.drop_column('priority')

    # Drop the taskpriority type
    taskpriority = sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority')
    taskpriority.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
