"""add_group_model_v2

Revision ID: 38d622ba3db7
Revises: e7d04c90bc13
Create Date: 2026-05-08 23:46:26.962849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d622ba3db7'
down_revision: Union[str, Sequence[str], None] = 'e7d04c90bc13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id'], name=op.f('fk_tbl_groups_user_id_tbl_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_groups')),
    sa.UniqueConstraint('user_id', 'name', name='uq_group_user_name')
    )
    with op.batch_alter_table('tbl_audit_logs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('tbl_subtasks', schema=None) as batch_op:
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_constraint(batch_op.f('fk_tbl_subtasks_user_id_tbl_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tbl_subtasks_task_id_tbl_tasks'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tbl_subtasks_user_id_tbl_users'), 'tbl_users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_tbl_subtasks_task_id_tbl_tasks'), 'tbl_tasks', ['task_id'], ['id'])

    with op.batch_alter_table('tbl_tags', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('tbl_task_tags', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_tbl_task_tags_task_tag'), type_='unique')
        batch_op.drop_column('id')

    with op.batch_alter_table('tbl_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_constraint(batch_op.f('fk_tbl_tasks_user_id_tbl_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tbl_tasks_user_id_tbl_users'), 'tbl_users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_tbl_tasks_group_id_tbl_groups'), 'tbl_groups', ['group_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('tbl_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tbl_tasks_group_id_tbl_groups'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tbl_tasks_user_id_tbl_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tbl_tasks_user_id_tbl_users'), 'tbl_users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('group_id')

    with op.batch_alter_table('tbl_task_tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_tbl_task_tags_task_tag'), ['task_id', 'tag_id'])

    with op.batch_alter_table('tbl_tags', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('tbl_subtasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tbl_subtasks_task_id_tbl_tasks'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tbl_subtasks_user_id_tbl_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tbl_subtasks_task_id_tbl_tasks'), 'tbl_tasks', ['task_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_tbl_subtasks_user_id_tbl_users'), 'tbl_users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('tbl_audit_logs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    op.drop_table('tbl_groups')
    # ### end Alembic commands ###
