"""add position to subtask

Revision ID: 4f7c8440bd82
Revises: 8f6a43cb7234
Create Date: 2026-05-13 07:31:50.535415

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4f7c8440bd82'
down_revision: Union[str, Sequence[str], None] = '8f6a43cb7234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_subtasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_subtasks', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
