"""Initial migration with Projects

Revision ID: 67fff7e05b96
Revises: 
Create Date: 2026-05-09 22:08:24.759576

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67fff7e05b96'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None



def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('confirmed', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('confirmation_failed', sa.Boolean(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_users')),
    sa.UniqueConstraint('email', name=op.f('uq_tbl_users_email'))
    )
    op.create_table('tbl_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id'], name=op.f('fk_tbl_audit_logs_user_id_tbl_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_audit_logs'))
    )
    op.create_table('tbl_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id'], name=op.f('fk_tbl_projects_user_id_tbl_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_projects')),
    sa.UniqueConstraint('user_id', 'name', name='uq_project_user_name')
    )
    op.create_table('tbl_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id'], name=op.f('fk_tbl_tags_user_id_tbl_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_tags')),
    sa.UniqueConstraint('user_id', 'name', name='uq_tbl_tags_user_name')
    )
    op.create_table('tbl_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['tbl_projects.id'], name=op.f('fk_tbl_tasks_project_id_tbl_projects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id'], name=op.f('fk_tbl_tasks_user_id_tbl_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_tasks'))
    )
    op.create_table('tbl_subtasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tbl_tasks.id'], name=op.f('fk_tbl_subtasks_task_id_tbl_tasks')),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id'], name=op.f('fk_tbl_subtasks_user_id_tbl_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tbl_subtasks'))
    )
    op.create_table('tbl_task_tags',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tbl_tags.id'], name=op.f('fk_tbl_task_tags_tag_id_tbl_tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tbl_tasks.id'], name=op.f('fk_tbl_task_tags_task_id_tbl_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'tag_id', name=op.f('pk_tbl_task_tags'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_task_tags')
    op.drop_table('tbl_subtasks')
    op.drop_table('tbl_tasks')
    op.drop_table('tbl_tags')
    op.drop_table('tbl_projects')
    op.drop_table('tbl_audit_logs')
    op.drop_table('tbl_users')
    
    # Drop custom enum type
    op.execute("DROP TYPE IF EXISTS taskpriority")
    # ### end Alembic commands ###
