"""add_position_field

Revision ID: 8f6a43cb7234
Revises: b09a9405a8af
Create Date: 2026-05-13 02:38:13.153833

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8f6a43cb7234'
down_revision: Union[str, Sequence[str], None] = 'b09a9405a8af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('tbl_tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_tags', schema=None) as batch_op:
        batch_op.drop_column('position')

    with op.batch_alter_table('tbl_projects', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
