"""Initial migration

Revision ID: a6e267909ed1
Revises:
Create Date: 2026-05-06 00:26:17.427876

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a6e267909ed1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Constants for duplicated literals
CURRENT_TIMESTAMP = '(CURRENT_TIMESTAMP)'
TBL_USERS_ID = 'tbl_users.id'


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text(CURRENT_TIMESTAMP), nullable=True),
    sa.Column('confirmed', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('confirmation_failed', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tbl_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text(CURRENT_TIMESTAMP), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [TBL_USERS_ID], name=op.f('fk_tbl_tags_user_id_tbl_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_tbl_tags_user_name')
    )
    op.create_table('tbl_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text(CURRENT_TIMESTAMP), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [TBL_USERS_ID], name=op.f('fk_tbl_tasks_user_id_tbl_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_subtasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text(CURRENT_TIMESTAMP), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tbl_tasks.id'], name=op.f('fk_tbl_subtasks_task_id_tbl_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], [TBL_USERS_ID], name=op.f('fk_tbl_subtasks_user_id_tbl_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_task_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text(CURRENT_TIMESTAMP), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tbl_tags.id'], name=op.f('fk_tbl_task_tags_tag_id_tbl_tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tbl_tasks.id'], name=op.f('fk_tbl_task_tags_task_id_tbl_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'tag_id', name='uq_tbl_task_tags_task_tag')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_task_tags')
    op.drop_table('tbl_subtasks')
    op.drop_table('tbl_tasks')
    op.drop_table('tbl_tags')
    op.drop_table('tbl_users')
    # ### end Alembic commands ###
