"""add_color_and_icon_to_tags_and_projects

Revision ID: c74d67078105
Revises: 67fff7e05b96
Create Date: 2026-05-11 02:37:25.498163

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c74d67078105'
down_revision: Union[str, Sequence[str], None] = '67fff7e05b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(), nullable=True))

    with op.batch_alter_table('tbl_tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('icon', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_tags', schema=None) as batch_op:
        batch_op.drop_column('icon')
        batch_op.drop_column('color')

    with op.batch_alter_table('tbl_projects', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
